### PR TITLE
Add support for cloudflare source in loadbalaner firewall rules

### PR DESCRIPTION
**Pull request by reubit**
## Description
Add support for cloudflare source in loadbalaner firewall rules

## Related Issues
Addresses #102 

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by reubit** [comment]
@vultj @happytreees @ddymko Just flagging you guys for review.

Thanks! 🙂

**Comment by optik-aper** [comment]
This looks sane to me and tests work locally.  @reubit If you wouldn't mind resolving the gofmt error we can merge this.
```
vultr/loadbalancer_test.go:95: File is not `gofmt`-ed with `-s` (gofmt)
			Name:        "lb-name",
			Namespace:   v1.NamespaceDefault,
			UID:         "lb-name",
```

**Comment by reubit** [comment]
Thanks @optik-aper. Just pushed the gofmt fix. Apologies for that!

**Comment by reubit** [comment]
@optik-aper \*\*Nudge\*\*

Just a gentle reminder to approve the workflows when you've got time.

Would be great to see this merged and included in the next VKE upgrade!

Thanks! :slightly_smiling_face:

**Pull request merged**
